language: node_js
node_js:
  - "6"
script: npm run build
branches:
  only:
  - source
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  repo: mjackson/mjackson.github.io
  target_branch: master
  local_dir: build
  on:
    branch: source
