language: node_js
node_js:
  - node
cache: yarn
script: yarn build
branches:
  only:
    - master
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  local_dir: build
  on:
    branch: master
