before_deploy:
  - yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  repo: mjackson/mjackson.github.io
  target_branch: master
  local_dir: build
  on:
    branch: master
